# Generated by Django 5.2.4 on 2025-08-13 00:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyReviews', '0002_alter_movie_average_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('birth', models.DateField(blank=True)),
                ('death', models.DateField(blank=True)),
                ('biography', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='movie',
            name='average_score',
        ),
        migrations.AddField(
            model_name='movie',
            name='date_added',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='number_reviews',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, default='fallback.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='movie',
            name='total_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MyReviews.movie'),
        ),
        migrations.AddField(
            model_name='movie',
            name='cast',
            field=models.ManyToManyField(blank=True, related_name='cast', to='MyReviews.person'),
        ),
        migrations.AddField(
            model_name='movie',
            name='crew',
            field=models.ManyToManyField(blank=True, related_name='crew', to='MyReviews.person'),
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MyReviews.person'),
        ),
    ]
