# Generated by Django 5.2.4 on 2025-08-15 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyReviews', '0005_alter_movie_director'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='runtime',
            field=models.IntegerField(),
        ),
    ]
