# Generated by Django 5.2.5 on 2025-09-25 14:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyReviews', '0014_remove_genre_genre_id_remove_movie_movie_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='contributors',
            field=models.ManyToManyField(blank=True, related_name='genre_contrib', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movie',
            name='contributors',
            field=models.ManyToManyField(blank=True, related_name='movie_contrib', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movie',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='person',
            name='contributors',
            field=models.ManyToManyField(blank=True, related_name='person_contrib', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='movie',
            name='director',
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre_list',
            field=models.ManyToManyField(blank=True, related_name='genre_list', to='MyReviews.genre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='death',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.ManyToManyField(blank=True, related_name='director', to='MyReviews.person'),
        ),
    ]
