# Generated by Django 5.2.5 on 2025-09-25 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('birth', models.DateField(blank=True, null=True)),
                ('death', models.DateField(blank=True, null=True)),
                ('biography', models.TextField(blank=True)),
                ('picture', models.ImageField(blank=True, default='profilefallback.png', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=40, unique=True)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('picture', models.ImageField(blank=True, default='profilefallback.png', upload_to='')),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('poster', models.ImageField(blank=True, default='fallback.png', upload_to='')),
                ('average_score', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('total_score', models.IntegerField(default=0)),
                ('number_reviews', models.IntegerField(default=0)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('runtime', models.IntegerField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('genre_list', models.ManyToManyField(blank=True, related_name='genre_list', to='MyReviews.genre')),
                ('cast', models.ManyToManyField(blank=True, related_name='cast', to='MyReviews.person')),
                ('crew', models.ManyToManyField(blank=True, related_name='crew', to='MyReviews.person')),
                ('director', models.ManyToManyField(blank=True, related_name='director', to='MyReviews.person')),
                ('contributors', models.ManyToManyField(blank=True, related_name='movie_contrib', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('score', models.IntegerField()),
                ('body', models.TextField(blank=True)),
                ('movie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movie', to='MyReviews.movie')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='contributors',
            field=models.ManyToManyField(blank=True, related_name='person_contrib', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='genre',
            name='contributors',
            field=models.ManyToManyField(blank=True, related_name='genre_contrib', to=settings.AUTH_USER_MODEL),
        ),
    ]
