# Generated by Django 5.2.4 on 2025-08-09 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyReviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='average_score',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
