# Generated by Django 5.2.5 on 2025-09-29 04:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyReviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
