# Generated by Django 5.2.4 on 2025-08-13 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyReviews', '0004_alter_movie_date_added_alter_review_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MyReviews.person'),
        ),
    ]
