# Generated by Django 5.2.4 on 2025-08-23 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyReviews', '0006_alter_movie_runtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre_list',
            field=models.ManyToManyField(blank=True, to='MyReviews.genre'),
        ),
    ]
