# Generated by Django 5.2.4 on 2025-08-26 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyReviews', '0007_user_is_staff_alter_movie_genre_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='average_score',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='picture',
            field=models.ImageField(blank=True, default='fallback.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, default='fallback.png', upload_to=''),
        ),
    ]
