# Generated by Django 5.2.4 on 2025-08-26 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyReviews', '0008_movie_average_score_person_picture_user_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='picture',
            field=models.ImageField(blank=True, default='profilefallback.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, default='profilefallback.png', upload_to=''),
        ),
    ]
