# Generated by Django 5.2.5 on 2025-09-21 01:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyReviews', '0009_alter_person_picture_alter_user_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='movie',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MyReviews.movie'),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
